using MediatR;
using Microsoft.EntityFrameworkCore;
using SupportDeskPro.Application.Interfaces;
using SupportDeskPro.Domain.Exceptions;

namespace SupportDeskPro.Application.Features.Tickets.GetAttachmentDownloadUrl;

/// <summary>
/// Generates a time-limited SAS signed URL for secure file download.
/// Validates the attachment exists and belongs to the requested ticket.
/// Container is private — direct blob URL access is blocked.
/// SAS URL is generated by BlobStorageService and expires after 24 hours.
/// </summary>
public class GetAttachmentDownloadUrlQueryHandler
    : IRequestHandler<GetAttachmentDownloadUrlQuery, string>
{
    private readonly IApplicationDbContext _db;
    private readonly IBlobStorageService _blobService;

    public GetAttachmentDownloadUrlQueryHandler(
        IApplicationDbContext db,
        IBlobStorageService blobService)
    {
        _db = db;
        _blobService = blobService;
    }

    public async Task<string> Handle(
        GetAttachmentDownloadUrlQuery request,
        CancellationToken cancellationToken)
    {
        // Validate attachment exists and belongs to the ticket
        var attachment = await _db.TicketAttachments
            .FirstOrDefaultAsync(
                a => a.Id == request.AttachmentId
                     && a.TicketId == request.TicketId
                     && !a.IsDeleted,
                cancellationToken)
            ?? throw new NotFoundException("Attachment", request.AttachmentId);

        // Generate SAS signed URL — expires after 24 hours
        var sasUrl = _blobService.GenerateSasUrl(attachment.StoredFileName);

        return sasUrl;
    }
}